---
title: "Venn Diagram"
author: "Chia-Te Wang"
date: '2022-06-28'
output: html_document
---
### This R script is for venn diagram junction tsv file data visualization

## Import library
```{r}
library(tidyverse)
library(VennDiagram)
```

## load data
```{r}
B.1.1.7 = read.delim("/Users/justin/Desktop/0712/noncanonical_sgRNA_Result/Alpha_sgRNA_junction_summary.tsv", header= FALSE, sep = "\t", col.names = c('j5', 'j3', 'count','startpos', 'productsize', 'chorm' ,'type' ,'name' ,'start' ,'end','evtype', 'evrelorf', 'evsize','startpos_byfusion'))
B.1.351 = read.delim("/Users/justin/Desktop/0712/Beta_result/Beta_sgRNA_junction_summary.tsv", header= FALSE, sep = "\t", col.names = c('j5', 'j3', 'count','startpos', 'productsize', 'chorm' ,'type' ,'name' ,'start' ,'end','evtype', 'evrelorf', 'evsize','startpos_byfusion'))
B.1.617.2 = read.delim("/Users/justin/Desktop/0712/noncanonical_sgRNA_Result/Delta_sgRNA_junction_summary.tsv", header= FALSE, sep = "\t", col.names = c('j5', 'j3', 'count','startpos', 'productsize', 'chorm' ,'type' ,'name' ,'start' ,'end','evtype', 'evrelorf', 'evsize','startpos_byfusion'))
P.1 = read.delim("/Users/justin/Desktop/0712/Gamma_result/Gamma_sgRNA_junction_summary.tsv", header= FALSE, sep = "\t", col.names = c('j5', 'j3', 'count','startpos', 'productsize', 'chorm' ,'type' ,'name' ,'start' ,'end','evtype', 'evrelorf', 'evsize','startpos_byfusion'))
B.1.1.529 = read.delim("/Users/justin/Desktop/0712/noncanonical_sgRNA_Result/Omicron_sgRNA_junction_summary.tsv", header= FALSE, sep = "\t", col.names = c('j5', 'j3', 'count','startpos', 'productsize', 'chorm' ,'type' ,'name' ,'start' ,'end','evtype', 'evrelorf', 'evsize','startpos_byfusion'))

## combine j5 and j3
B.1.1.7$JS <- paste(B.1.1.7$j5,"-",B.1.1.7$j3)
B.1.351$JS <- paste(B.1.351$j5,"-",B.1.351$j3)
B.1.617.2$JS <- paste(B.1.617.2$j5,"-",B.1.617.2$j3)
P.1$JS <- paste(P.1$j5,"-",P.1$j3)
B.1.1.529$JS <- paste(B.1.1.529$j5,"-",B.1.1.529$j3)
```

## sum up by JS
```{r}
B.1.1.7 <- aggregate(count ~ JS , B.1.1.7, sum) 
B.1.1.7 <- filter(B.1.1.7, count != 0) 
B.1.1.7 <- arrange(B.1.1.7,desc(count))
B.1.351 <- aggregate(count ~ JS , B.1.351, sum) 
B.1.351 <- filter(B.1.351, count >= 100) 
B.1.351 <- arrange(B.1.351,desc(count))
B.1.617.2 <- aggregate(count ~ JS , B.1.617.2, sum) 
B.1.617.2 <- filter(B.1.617.2, count != 0) 
B.1.617.2 <- arrange(B.1.617.2,desc(count))
P.1 <- aggregate(count ~ JS , P.1, sum) 
P.1 <- filter(P.1, count >= 100) 
P.1 <- arrange(P.1,desc(count))
B.1.1.529 <- aggregate(count ~ JS , B.1.1.529, sum) 
B.1.1.529 <- filter(B.1.1.529, count != 0) 
B.1.1.529 <- arrange(B.1.1.529,desc(count))
```

## generate plot (default = 5)
```{r}
plot <- venn.diagram(list(Alpha=B.1.1.7$JS,Beta=B.1.351$JS,Delta=B.1.617.2$JS,Gamma=P.1$JS,Omicron=B.1.1.529$JS),
                     filename = NULL,
                     main = "Variant sgRNA comparison",
                     main.cex = 1.5,
                     fill =c("blue","orange","yellow","red","gray"))
grid.newpage()
grid.draw(plot)
ggsave(file.path("./venndiagram.pdf"), plot, width = 20, height = 13, units = "cm")
```

## output potential junction site
```{r}
##seq by "\t", col.names=JS
intersect <- data.frame(JS=intersect(B.1.351$JS,B.1.1.529$JS))
write.table(intersect, file="./noncanonical_sgRNA_Result/Beta_Omicron.tsv", quote=FALSE, sep='\t', col.names = TRUE,row.names = FALSE)
##https://stackoverflow.com/questions/17108191/how-to-export-proper-tsv
intersect2 <- data.frame(JS=intersect(B.1.617.2$JS,B.1.1.529$JS))
write.table(intersect2, file='./noncanonical_sgRNA_Result/Delta_Omicron.tsv', quote=FALSE, sep='\t', col.names = TRUE,row.names = FALSE)
intersect3 <- data.frame(JS=Reduce(intersect, list(B.1.617.2=B.1.617.2$JS,B.1.351=B.1.351$JS,B.1.1.529=B.1.1.529$JS)))
write.table(intersect3, file='./noncanonical_sgRNA_Result/Beta_Delta_Omicron.tsv', quote=FALSE, sep='\t', col.names = TRUE,row.names = FALSE)
```

```{r}
intersect <- data.frame(JS=intersect(B.1.351$JS,P.1$JS))
write.table(intersect, file="./Beta_Gamma.tsv", quote=FALSE, sep='\t', col.names = TRUE,row.names = FALSE)
```


### Example Code
## Echo intersection (two dataframe)
```{r}
intersect <- data.frame(JS=intersect(betaJS$JS,OmicronJS$JS),)
write.table(intersect, file='./JS.tsv', quote=FALSE, sep='\t', col.names = TRUE,row.names = FALSE)
#https://stackoverflow.com/questions/17108191/how-to-export-proper-tsv
```

## Echo intersection (multiple input)
```{r}
Reduce(intersect, list(beta_1=beta_1$JS,beta_2=beta_2$JS,beta_3=beta_3$JS,beta_4=beta_4$JS,beta_5=beta_5$JS))
#https://www.r-bloggers.com/2012/06/intersect-for-multiple-vectors-in-r/
```

## Generate plot with label (Failed!)
```{r}
plot <- venn.diagram(list(beta_1=beta_1$JS,beta_2=beta_2$JS,beta_3=beta_3$JS,beta_4=beta_4$JS,beta_5=beta_5$JS),
                     filename = NULL,
                     main = "Variant Junction Site",
                     main.cex = 1.5,
                     fill =c("blue","orange","yellow","red","gray"))
# have a look at the names in the plot object v
lapply(plot,  names)
# We are interested in the labels
lapply(plot, function(i) i$label)
plot[[8]]$label <- paste(Reduce(intersect, list(beta_1=beta_1$JS,beta_2=beta_2$JS,beta_3=beta_3$JS,beta_4=beta_4$JS,beta_5=beta_5$JS)), collapse="\n") 
grid.newpage()
grid.draw(plot)
#ggsave(file.path("./JS_venn.pdf"), plot, width = 30, height = 15, units = "cm")
```

## Load data (excel file)
```{r}
library(openxlsx)
Name <- read.xlsx("$filefullpath/filename.xlsx",sheet = "工作表1")
```

## Combine all dataframe
```{r}
Variant = list(B.1.1.7,B.1.351,B.1.617.2,P.1,B.1.1.529)
VariantJS <- Variant %>% reduce(full_join)
##https://www.delftstack.com/zh-tw/howto/r/merge-in-r/
```

